### PR TITLE
refactor: split up game into scripts

### PR DESCRIPTION
**Pull request by ram02z**
﻿## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Documentation change
- [ ] Tests

[Trello Link](https://trello.com/c/kLZGCdh4/25-implement-space-invaders-game-scene)

## Proposed Changes

This PR works on merging and splitting up the game from #6 into subscripts to make it easier to test. The game ending and the words are still in progress, however we have two tickets on Trello to track both.

### CODE REVIEW

**Review by EthanTB — APPROVED** [review]
Looks like a good start and will be useful groundwork for developing the translation game as outlined in the requirements. Some bugs are present such as the player being able to move off screen but it is still a good starting point. More comments for methods/classes would be helpful. The rest looks good :)

**Comment by ram02z** [comment]
Ah, nice catch. I made a change to the player ship and it resulted the boundaries not working, should be all good now! I'll hold off on merging in this until I write a few tests (so the bug doesnt happen again lol) and more comments

**Comment by EthanTB** [comment]
image
I received this error in the console after shooting an asteroid. it seems there is an issue with the following method 
image
Looks like checks need to be added to see if the queue is null. Also needs comments and unit testing.

**Comment by ram02z** [comment]
Error should be fixed on the latest commit. I removed the code that cycles through the array by accident.

I'll add the tests on a branch on top of this so it's easier to review (GitHub diff is a clusterfuck ATM)

**Comment by EthanTB** [comment]
> Error should be fixed on the latest commit. I removed the code that cycles through the array by accident.
> 
> I'll add the tests on a branch on top of this so it's easier to review (GitHub diff is a clusterfuck ATM)

Ok cool fine with me looks good to merge then! :)

**Pull request merged**
